### ISSUE TITLE
Are Personal-ish Sites Allowed?

### ISSUE THREAD

**Issue by basementcommunity** [ericwbailey/a11y-webring.club#106]
### Your issue

Hello. I am one person currently running my web forum https://basementcommunity.com.

It's an internet discussion board for general and focused topics with no real intent on making money or being a business, but really just a hobby project for myself with a goal of creating a community of people fatigued from modern social media.

That being said, I'm a huge a11y advocate and pride myself on making my site as accessible as possible. But I'm not planning on revealing my identity willingly for the foreseeable future.

So the question is, are sites like mine allowed to join the webring?

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
Hey there, I want to communicate a couple of things:

1. Thank you for your interest, and for considering this webring for the community you cultivated. Seeing things like that warms my heart.
2. Also thank you for your patience with me getting back to this. I've been going through a lot of job, life, and health-related stress lately, and things like this had to be deprioritized. 

I've been thinking about the request via the lenses of the site's mission and your expressed desire for anonymity. I take community building and privacy seriously, and have a ton of respect for others who do as well.

I think where I land on this issue and [its companion PR](https://github.com/ericwbailey/a11y-webring.club/pull/107) is that communities are less in line with the overall goal of the webring. Quoting the tagline here:

>A webring for digital accessibility practitioners.

A discussion board seems a little less inline with that goal, and consequently I don't think I should add the Basement community forum. It also raises the question of the accessibility of user generated content, which increases the surface area of content to monitor for inclusive practices to a degree that I don't have the ability to stay on top of. Basically, I want the webring list to have more of a promise of accessible content than not and that complicates things.

As for anonymity, I do think that is something the webring should (and does) support. Aliases are acceptable for a web presence on the webring. The security of the chain of technology used to create that anonymity is beyond the scope of this website, but the underlying considerations about it is why I draw the line at requiring HTTPS.

All this said, I'd like to keep this issue open until the following questions are addressed, if you're willing:

- Are there opportunities for improvement in the documentation to better communicate these concerns? Both on the site itself and GitHub?
- Is there any other information you feel is not present or could use improvement?

And again, thank you for your interest and patience here.

**Comment by ericwbailey** [comment]
Closed for inactivity.
