### ISSUE TITLE
Consider checking for build errors as a pre-commit check

### ISSUE THREAD

**Issue by sivakusayan** [ericwbailey/a11y-webring.club#124]
### Your issue

I noticed that commits after c40ce94ba385ace0c7c01d736ca3ff015bdb2aa3 weren't being reflected on the live site - this is because of a syntax error in the JSON that was committed. 

Besides fixing the syntax error, would it make sense to add a Github Action to make sure the site builds? If that makes sense, I wouldn't mind making a pull request for it.

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
@sivakusayan I'd love help with that, thank you! Apologies for the delay in reply, as well.

**Comment by sivakusayan** [comment]
No worries, I get how busy life can get - I've done it too 🙂
