### ISSUE TITLE
Remove Twitter?

### ISSUE THREAD

**Issue by ericwbailey** [ericwbailey/a11y-webring.club#131]
Twitter's [most recent issues with antisemitism](https://www.adl.org/resources/press-release/adl-statement-xtwitter) sits poorly with me. To me, it's an inflection point where the platform is now actively stoking and profiting from fomenting hate.

This is balanced against it being a place where a lot of disability advocates organize, as well as its relatively low barrier of adoption.

I was wondering if we could talk about this, and folks' opinions on the matter. 

@acnorrisuk, @AliciaJarvis, @segdeha, @itscrisdiaz, @dnikub, @dsenneff, @davidakennedy, @dennisl, @dpersing, @codeability, @FMJansen, @worldsayer, @jrfbz, @jenstrickland, @joshkimux, @adeleke5140, @mattobee, @matthewdeeprose, @mherchel, @mikemai2awesome, @bamadesigner, @racheleditullio, @saptaks, @SteveFaulkner, @stevenwoodson, @tiffanypender, @toddlibby, @1Copenut, @winniebosy: Apologies for the mass-tag, but this was the only way I could think of for people on the webring who have Twitter profiles to be aware this was being discussed.

And speaking of social media: I just [added support for GitHub](https://github.com/ericwbailey/a11y-webring.club/pull/129) if you're interested in updating your info.

**Comment by segdeha** [comment]
Yikes. I can't say I'm surprised at El°n's actions, but at some point it merits action. Personally, I think the platform stepped over the line a long time ago when it dragged its heels for years before it de-platformed Trvmp.

All of us creating content for the site is adding value to it. One small thing I might do is make my profile private so I'm not contributing in that way. Curious what others think would be effective ways to stand up to this kind of behavior?

**Comment by SaptakS** [comment]
I am +1 to removing Twitter. I have primarily stopped posting there (apart from reading other's content). I will send PR to add my GitHub.

**Comment by mattobee** [comment]
I have already made my Twitter profile private and had been meaning to remove the links from my website and anywhere else it appears. Thanks for the reminder! For me, it's just not a pleasant or productive place to be any more. I have no objection if other people want to keep their Twitter links though.

**Comment by mherchel** [comment]
I'm bummed that Twitter is circling the toilet. I used to really love it, and Mastodon isn't quite the same. Oh well. Do what needs to be done. 

I miss old social media. Twitter and FB from 10 years ago before they were selling all of your data, and promoting conspiracy theories.

**Comment by 1Copenut** [comment]
I engage with a fair number of a11y advocates and practitioners on Twitter, but the direction of the service has been weighing on me. I do and would support a decision to remove Twitter. I'm sad to see it go, but that underscores why groups like this webring are important.

**Comment by ItsCrisDiaz** [comment]
I'm going to be honest, as a Latin American, Twitter is where most Spanish-speaking tech community is so it helps me with reach when I publish my blogs/articles about a11y, and despite still having a limited reach about a "niche" topic (again, in the context of Spanish-speaker community) it has helped to spread awareness about a11y.

With that said, I'm good with removing Twitter. As you might have heard, Elon is thinking of charging everybody on Twitter so it'll kill the platform anyways, so I guess I'll look for a better way to promote the content I make.

So yeah, remove Twitter, I think it's for the best.

**Comment by worldsayer** [comment]
This is a prescient reminder, thank you. I've removed links to Twitter from my website. Certainly wouldn't be replacing the bird icon with the new logo, nor using the new name. If the webring removes listings of our Twitter profiles, I'd support that.

While it pales in comparison to what the accessibility community on Old Twitter was, the best alternative I've found (such as it is) has been BlueSky. (If any of you want an invite, I have codes.)

If Mastodon is supported, would it be worth adding support for BlueSky? Too soon?

**Comment by stevenwoodson** [comment]
I vote to remove it as well.

To quote from the FAQ, the goal of this webring was to provide "a way to discover people doing good work in the digital accessibility space" by cross linking our respective websites.

The addition of social profiles, to me, was a bonus and removing one of them doesn't take away from that primary goal. People can decide to leave a link to Twitter on their webring listed website, so it'll still be discoverable by folks that are truly interested in continuing to engage there.

**Comment by TiffanyPender** [comment]
Thanks for bringing awareness to this. I have greatly decreased my activity on Twitter over time for various reasons. I also support the decision to remove it.

**Comment by colabottles** [comment]
I have no issues with the removal of Twitter at all. I will fully support the decision to do so. My time on there is very limited as of late with all the ableism in the past few days and no change in sight as far as all the other issues that site has being led by Apartheid Clyde. I am not a fan of what has been done and the factors behind it even before the sale.

So full support from me.

**Comment by jenstrickland** [comment]
Happy to remove Twitter from the WebRing details.

Like @ItsCrisDiaz I recognize that people of color and others still find use in Twitter, although I agree that's likely to fall aside with Husk's new direction.

**Comment by bamadesigner** [comment]
I am happy to remove Twitter from my member details. I have stopped posting on Twitter, but leave the link on my website out of some weird false hope and longing for yesteryear.

I agree with @stevenwoodson that folks can link to their Twitter on their website if they wish to do so.

**Comment by ericwbailey** [comment]
>I'm bummed that Twitter is circling the toilet. I used to really love it, and Mastodon isn't quite the same. Oh well. Do what needs to be done.

>I engage with a fair number of a11y advocates and practitioners on Twitter, but the direction of the service has been weighing on me.

I also wanted to communicate that I really agree and feel these sentiments deeply. It's frustrating and a huge loss in so many ways.

>I'm going to be honest, as a Latin American, Twitter is where most Spanish-speaking tech community is so it helps me with reach when I publish my blogs/articles about a11y, and despite still having a limited reach about a "niche" topic (again, in the context of Spanish-speaker community) it has helped to spread awareness about a11y.

>Like @ItsCrisDiaz I recognize that people of color and others still find use in Twitter, although I agree that's likely to fall aside with Husk's new direction.

I also wanted to highlight these comments, and thank you for vocalizing them. Being able to move away from the platform is a privilege in some ways, and many of those ways are easier for my identify. This is one of the reasons I wanted to talk about opinions about doing this before committing to it. 

>If Mastodon is supported, would it be worth adding support for BlueSky? Too soon?

I don't mind doing this! Personally-speaking, it has been nice to see other accessibility folks I know from Twitter popping up there. I also have a few invite codes if webring members here are interested.

>To quote from the FAQ, the goal of this webring was to provide "a way to discover people doing good work in the digital accessibility space" by cross linking our respective websites.

One of the not-so-secret reasons I made this was to stay in touch with all the folks in the space I know and respect, so I'm so damn happy to have y'all here and chatting about this 💜

**Comment by matthewdeeprose** [comment]
I agree with everyone's comments. I'm still using twitter as "EdTech" (Educational Technology) conversations are still ongoing and useful. I'll leave a twitter link on my page, but totally happy to have the twitter aspect removed from the webring details.

**Comment by 1Copenut** [comment]
@ericwbailey If you've still got Bluesky invite codes that aren't spoken for, I would request one. LMK a good way to DM my email address. Much appreciated.

**Comment by ItsCrisDiaz** [comment]
That sounds like a weird place to say it, but given the interest, I have a couple of Bluesky codes if someone needs them!

**Comment by winniebosy** [comment]
@ItsCrisDiaz I need one, please!

**Comment by ItsCrisDiaz** [comment]
> @ItsCrisDiaz I need one, please!

Done! I sent it to the contact email on your website

**Comment by davidakennedy** [comment]
I agree with the other folks who have chimed in here. I'm good with removing Twitter. I don't spend much time there because it seems like a place hostile to most humans and communities these days.

**Comment by adeleke5140** [comment]
Twitter was the first place I came across @ericwbailey content on a11y so I am quite sad to see how the platform has turned out. I really wish there can be a better marketsquare of flourishing ideas. I am okay with taking it out.

Also @ItsCrisDiaz Thanks for mentioning bluesky, do you by chance have any more invites?

**Comment by ItsCrisDiaz** [comment]
> Twitter was the first place I came across @ericwbailey content on a11y so I am quite sad to see how the platform has turned out. I really wish there can be a better marketsquare of flourishing ideas. I am okay with taking it out.
> 
> Also @ItsCrisDiaz Thanks for mentioning bluesky, do you by chance have any more invites?

Sure, I sent it to the email is on your website

**Comment by mikemai2awesome** [comment]
Yup remove it

**Comment by ericwbailey** [comment]
Alrighty folks, it appears like we have consensus. I'll be closing this issue with https://github.com/ericwbailey/a11y-webring.club/pull/142 merged. 

Thank you for your input here, I really appreciate it. I also hope our community finds a place it can settle again sometime soon 💜
