### ISSUE TITLE
Accessibility statement: Requires JS to view due to linking to GitHub

### ISSUE THREAD

**Issue by lanodan** [ericwbailey/a11y-webring.club#155]
The footer on the website links to <https://github.com/ericwbailey/a11y-webring.club/blob/main/.github/ACCESSIBILITY_STATEMENT.md> which requires a browser with github-compliant JavaScript to view, I would consider this an accessibility issue.

And given it's a rather simple markdown page, shouldn't it be hosted on the site itself?

**Comment by ericwbailey** [comment]
Nah.
