### ISSUE TITLE
[Bug] Webring links crash in browser

### ISSUE THREAD

**Issue by basher** [ericwbailey/a11y-webring.club#156]
### What happened?

All the links (previous / next / random) crash in browser.

![webring-crashed](https://github.com/ericwbailey/a11y-webring.club/assets/452809/282aed58-ada7-4fb2-b698-7071b62f2649)

### Operating systems

Windows 10

### Browsers

Firefox, Chrome

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
I think https://github.com/ericwbailey/a11y-webring.club/issues/156 fixed it! I'm able to get to to go next, previous, and random entries again. 

Closing, but please comment if your experience is different.
