### ISSUE TITLE
Style improvement suggestion: Member name line height and gap

### ISSUE THREAD

**Issue by helenclx** [ericwbailey/a11y-webring.club#185]
### Your issue

I noticed that when the webring website is viewed on a mobile device, particular on a vertical screen, member names with more than one line look cramped to the extent that the text appears to be overlapping, making the names difficult to read. For example:

![Screen Shot 2024-06-01 at 14 33 27](https://github.com/ericwbailey/a11y-webring.club/assets/119173961/a72deb3c-d8cd-47ef-8f03-120038acd6a3)

I forked the repo and looked into the CSS, and realised that it was because the line height of the member name (`.c-member` > `.view-as-list &`) was set to only 1, so my suggestion would be increasing the line-height of the member names. For instance, this is what it would look like if the line height is increased to 1.5:

![Screen Shot 2024-06-01 at 14 33 46](https://github.com/ericwbailey/a11y-webring.club/assets/119173961/2b1bb848-b391-4f2e-aa7e-d4e8d848dfef)

Another styling improvement suggestion I have for improving the member list style on mobile is adding a gap between member name and member social, since the lack of gap makes some member names and socials look cramped together, like this:

![Screen Shot 2024-06-01 at 14 37 29](https://github.com/ericwbailey/a11y-webring.club/assets/119173961/030aa691-27ae-45d5-b791-476f01815dcf)

This is what it would look like if `gap: 0.5rem` is added to the `.c-member` > `.view-as-list & selector:

![Screen Shot 2024-06-01 at 14 40 06](https://github.com/ericwbailey/a11y-webring.club/assets/119173961/85979d92-02be-4dd7-8cee-d05f927f1994)

I can create a PR with my suggestions if wanted.

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
Hi there! Thanks for reporting this, as well as your patience with me getting to it, and also your offer to fix it. 

It's been on my list to tweak for awhile now, along with some other things. I just addressed it in https://github.com/ericwbailey/a11y-webring.club/pull/190, so I'll be closing this issue as addressed. I appreciate the detail in your issue report, as well 🙂

**Comment by helenclx** [comment]
No problem. Thank you for your response and improvement to the website layout. 👍
