### ISSUE TITLE
[Bug] Prev/Random/Next links go to Netlify "This function has crashed" page

### ISSUE THREAD

**Issue by stevenwoodson** [ericwbailey/a11y-webring.club#202]
### What happened?

I tried on a few sites and browsers first to make sure it wasn't something isolated to one, happening in all cases. When I try the Previous, Random, and Next links on any participating site (including the main homepage at https://a11y-webring.club/) I get a Netlify error page "This function has crashed" with the following details:

```
An unhandled error in the function code triggered the following message:

Runtime.UserCodeSyntaxError - SyntaxError: Unexpected token ':'

Stack trace
Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token ':'
    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)
    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)
    at async start (file:///var/runtime/index.mjs:1282:23)
    at async file:///var/runtime/index.mjs:1288:1

Connection details
Netlify internal ID: 01J9MATN03KMKXKTEE7SZ6CEVS
```

### Operating systems

Mac

### Browsers

Tested in Chrome, Firefox, and Safari

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
@stevenwoodson I think I got a fix for this. Can you confirm that it's working on your end?

**Comment by stevenwoodson** [comment]
Working, thanks for fixing it @ericwbailey!
