### ISSUE TITLE
Document the need for a referrer header

### ISSUE THREAD

**Issue by Seirdy** [ericwbailey/a11y-webring.club#52]
### Your issue

This webring seems to require the use of the HTTP `referer` (sic) header. However, personal sites that don't monetize data or use analytics often drop referrers with a `Referrer-Policy: no-referrer` response header. A workaround is to override this with a `referrerpolicy` attribute on anchor elements, as I do in my webring template.

Documenting this could avoid future headaches as people wonder why their webring links don't work.

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
Oh, interesting! So, something like:

```html
<a href="https://a11y-webring.club/prev" rel="previous external" referrerpolicy="strict-origin">
  Previous website
</a>
```

**Comment by Seirdy** [comment]
Yes, but I'd probably drop the rel-prev since that's more appropriate for pagination, e.g. for combining pages in reader-mode.

-- 
Seirdy (https://seirdy.one)

**Comment by ericwbailey** [comment]
Closing via https://github.com/ericwbailey/a11y-webring.club/pull/75. Thank you for the guidance here, it's really appreciated!
