### ISSUE TITLE
[Feature suggestion] Support linking to an accessibility statement

### ISSUE THREAD

**Issue by Seirdy** [ericwbailey/a11y-webring.club#71]
### Feature suggestion

Some personal websites have accessibility statements, such as the kind recommended by the WAI. Linking to that alongside socials could be a nice touch.

### Who would you like to work on this feature?

- [ ] I would like to work on this feature
- [ ] I would like the site maintainers to work on this feature

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
Another excellent suggestion, thank you! 

I'm thinking one for the webring itself, as well as supporting it per-member in their JSON. It's still small enough that I think I could reach out to existing members to see if they'll update their info, too.

**Comment by ericwbailey** [comment]
Closed via https://github.com/ericwbailey/a11y-webring.club/pull/110.

@Seirdy Just wanted to communicate that: 

- Again, this is a lovely idea.
- Process for how existing sites will be handled is in the PR linked to in this comment, and
- Apologies for the time it took to get back to this. This is something I should have launched with.
