### ISSUE TITLE
Winnie’s site is down

### ISSUE THREAD

**Issue by FMJansen** [ericwbailey/a11y-webring.club#80]
### Your issue

@winniebosy’s site (https://bosibori.netlify.app/) is down on Netlify it seems, breaking the ring.

The social media links are still fine, though.

Related to `/data/members/Winnie%20Bosibori.json`

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
Thanks for reporting this, @FMJansen. I've moved @winniebosy entry into a new `removed/` directory in `data/`. See https://github.com/ericwbailey/a11y-webring.club/pull/82. 

I'm thinking this is a good intermediary measure between being listed and complete deletion, where the site might be temporarily 404ing, but may not be permanently offline. I'm using social presence as part of this decision.

I would also eventually like to incorporate this kind of thing into what https://github.com/ericwbailey/a11y-webring.club/pull/40 proposes.

**Comment by FMJansen** [comment]
Oh both sound really fair!

**Comment by winniebosy** [comment]
@ericwbailey  Facing some issues with the site but I will be back up soon

**Comment by FMJansen** [comment]
Looks like the website is back up, right @winniebosy? :D

**Comment by ericwbailey** [comment]
Closed via https://github.com/ericwbailey/a11y-webring.club/pull/92. Welcome back! 🙌

**Comment by winniebosy** [comment]
Thanks Eric
