### ISSUE TITLE
[Bug] Netlify function invocation fails

### ISSUE THREAD

**Issue by thibaudcolas** [ericwbailey/a11y-webring.club#88]
### What happened?

Using the "Previous", "Random", "Next" links results in a Netlify error page:

```
An unhandled error in the function code triggered the following message:

Runtime.UserCodeSyntaxError - SyntaxError: Unexpected token ':'
```

### Operating systems

N/A

### Browsers

N/A

### Code of conduct

- [X] I agree to follow this project's code of conduct

**Comment by ericwbailey** [comment]
Thanks for reporting this. I think I have a fix with https://github.com/ericwbailey/a11y-webring.club/pull/89, but keeping open to verify for now.

**Comment by luce-carevic** [comment]
It seems it's fixed! :)

**Comment by ericwbailey** [comment]
Woo!
